### ISSUE TITLE
Would you consider using JavaScript? When will you add a search function?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [freedit-org/freedit#101]
The current image upload function of freedit cannot display the uploaded image directly in the content box, which is a bit inconvenient to use

**Comment by freedit-dev** [comment]
The main reasons for the existence of Freedit are privacy and security. It is a great temptation to enable js for some convenience.

It may be added in a site setting as an optional feature.

As for search, I have tested [sonic](https://github.com/valeriansaliou/sonic) in my private project. It works well but there is no adoption of freedit, and I don't think it's urgent to add search function.
