### ISSUE TITLE
Simple Monochrome UI Design for Freedit

### ISSUE THREAD

**Issue by johnhorsema** [freedit-org/freedit#110]
Just created some concept UI for Freedit. Hope we can implement this so that Freedit can have a better UI and user experience.
Any thoughts?

![Public Channel View](https://github.com/freedit-org/freedit/assets/10090182/b1248b72-64ae-4112-b344-c6195a999bdf)
![Tag View](https://github.com/freedit-org/freedit/assets/10090182/1aaf2776-7758-4c5a-95a0-db967aaf8f93)

**Comment by freedit-dev** [comment]
https://lihkg.com Style?

**Comment by johnhorsema** [comment]
Not really. Right now freedit is static HTML + CSS.
lihkg is using React under the hood.

We can start with this basic template and allow customisation like themes / settings later.

**Comment by johnhorsema** [comment]
@freedit-dev Saw the UI from https://libreddit.freedit.eu/r/rust. It's a good starting point for the freedit's default ui. We can create themes based on this UI.

**Comment by freedit-dev** [comment]
@johnhorsema Thanks, fell free to ask anything you want to know from me. As you have found, I copied the ui from libreddit.

**Comment by johnhorsema** [comment]
@freedit-dev I thought you also built libreddit? The default freedit theme is Bulma correct?

**Comment by freedit-dev** [comment]
> @freedit-dev I thought you also built libreddit? The default freedit theme is Bulma correct?

I just deploy it. https://github.com/libreddit/libreddit
