### ISSUE TITLE
Supporting Lemmy API

### ISSUE THREAD

**Issue by erlend-sh** [freedit-org/freedit#115]
Any interest in supporting the Lemmy API as an alternative to Reddit?

https://users.rust-lang.org/t/building-a-better-r-rust-together/95194

**Comment by freedit-dev** [comment]
I have a little interest but I don't know how can I help.

**Comment by erlend-sh** [comment]
Looks like others are looking into the same thing: https://github.com/burhan-syed/troddit/issues/167

https://github.com/derivator/tafkars

**Comment by freedit-dev** [comment]
@erlend-sh I don't know what your plan is. Find a new place that users could post and comment? Or it must support ActivityPub? Or it has all old posts from r/rust?

**Comment by erlend-sh** [comment]
- we are setting up a Lemmy instance as an alternative to /r/rust
- It supports AP, which means it’s connected to the fediverse of 10 million users.
- We probably don’t need all old posts, just new ones.

On that last point, that’s where tafkars by @derivator comes in. If existing Reddit clients can learn to talk with Lemmy as well, then people’s browsing experience could continue with minimal friction.
