### ISSUE TITLE
replace sled with other databases

### ISSUE THREAD

**Issue by meypod** [freedit-org/freedit#139]
Hi
as you may be aware, or not, sled is not a reliable DB at the moment: 
https://github.com/spacejam/sled/issues
https://gitlab.com/famedly/conduit/-/issues/74
https://github.com/subconsciousnetwork/noosphere/issues/607

and the rewrite seems to be slow:
https://github.com/komora-io/marble

so to me it makes sense to move away from sled as soon as possible

it would be nice if we could easily swap the db with the db of our choice, for example what I have in mind is [ScyllaDB](https://www.scylladb.com/)

**Comment by freedit-dev** [comment]
Sled is catching up rapidly! And it's not easy to replace sled.

I'm watching sled closely. I have some problems with Sled when my db is about 50 GB(with compression enabled v0.34). But It's being actively developed. If Sled 1.0 makes me disappointed, I'll change it.
