### ISSUE TITLE
Add option to disable avatars

### ISSUE THREAD

**Issue by meypod** [freedit-org/freedit#140]
Hi
It would be nice if we could disable avatars globally

**Comment by freedit-dev** [comment]
Sorry, I don't get it. Why should be like that?

**Comment by meypod** [comment]
Avatars waste bandwidth and are distracting
They also take space when they appear in front-page next to post title
So it would be nice if server admin could disable them for their instance

**Comment by freedit-dev** [comment]
> Avatars waste bandwidth and are distracting They also take space when they appear in front-page next to post title So it would be nice if server admin could disable them for their instance

I just thought twice about your suggestion. In my opinion, the author is as important as posts for a community. More space for author is encouraging them to post better content.

I will not add this feature at the moment. If you deploy a website using freedit and it proves the feature is really needed, I'll change my mind.

**Comment by Jhonfunk** [comment]
@freedit-dev 

It would be nice that freedit allows admin to set an url. 

when a user uploads a file, freedit calls this url to dump the file to another server and gets the url of the dumped file.

**Comment by freedit-dev** [comment]
@Jhonfunk Do you mean that save images(user upload imgs or avatars) in service like S3? It's a good idea. I'll add this feature if someone really needs it.

**Comment by Jhonfunk** [comment]
@freedit-dev 
Yes, this is a very useful feature. Static files uploaded to S3 can reduce the load on freedit.
