### ISSUE TITLE
Add password recovery function

### ISSUE THREAD

**Issue by Yakumo-Yukari** [freedit-org/freedit#142]
When users forget their passwords without a password recovery feature, it's a terrible situation for them.

The current password reset and recovery process requires users to have a code prepared in advance, which can be fatal for users if they haven't prearranged a recovery code.

Perhaps we can incorporate an email-based password recovery feature.

**Comment by freedit-dev** [comment]
Maybe just inform user to generate a recovery code ?

**Comment by Jhonfunk** [comment]
For regular users, it is more convenient to send the temporary recovery code to the email address they used to register.

For example, allow the administrator to set a url for sending emails. 

When a user performs a password reset, freedit generates a temporary recovery code and then calls the url set by the administrator to send the email.

**Comment by freedit-dev** [comment]
First, I want freedit to be friendly to non-technical people and to be easy to install and use. So I hope everything could be done in one click/one command. I hope Freedit could be used without any additional SMTP server.

Secondly, I hope Freedit will put privacy first. Emails would be the most vulnerable part of the system. So I hope Freedit could be used without any email address. Not everyone will use temp mail.

Keeping the recovery code is easy: just send yourself an email or keep the recovery code in a draft message. In my opinion, our main job is to guide users to do this.

**Comment by Jhonfunk** [comment]
@freedit-dev 
The recovery code itself is pretty geeky stuff. guide users to do this is the hard way. but I respect your idea of privacy.
