### ISSUE TITLE
Strange things about `CONFIG.addr`

### ISSUE THREAD

**Issue by Jhonfunk** [freedit-org/freedit#144]
https://github.com/freedit-org/freedit/blob/4897ae17ecda59ea60f306e17ee2896b9b14e71b/src/config.rs#L65

1. change the default binding address to [::]:3001
2. `println!("{:?}", CONFIG.addr);` in main.rs and the results is `:::3001` (somehow the `[]` have been removed)
3. this will always cause `let addr = CONFIG.addr.parse::<SocketAddr>().unwrap();` panic

**Comment by freedit-dev** [comment]
`[::]:3001` functions well for me.
