### ISSUE TITLE
Global topping(Pin) is necessary

### ISSUE THREAD

**Issue by Jhonfunk** [freedit-org/freedit#146]
There are some important notifications that need to be topped on any page so that users can notice them.

**Comment by freedit-dev** [comment]
Maybe a site notification is better

**Comment by Jhonfunk** [comment]
I'm not exactly sure what you mean.

- If you mean sending a notification message to all users in their message boxes, I don't think that's a good idea.
- If you mean adding a separate table with all posts in this table topped above the user's posts, then this is good.

**Comment by freedit-dev** [comment]
@Jhonfunk I mean adding an announcement box on the side

**Comment by Jhonfunk** [comment]
@freedit-dev 
sidebox is really not a substitute for global topping.
