### ISSUE TITLE
Remove `Date`  field from http response headers

### ISSUE THREAD

**Issue by Jhonfunk** [freedit-org/freedit#152]
- The axum framework automatically adds a `date` field to every http response.

- I have tested and found that the `date` field in the Response headers could cause the cloudflare cache duration judgment to be abnormal, resulting in frequent cache loss or expiration.

- I'm not familiar with axum framework, after 3 hours of efforts did not find the relevant code.

**Comment by freedit-dev** [comment]
https://freedit.eu/post/1/5#4

What's your cloudflare catch setting？

**Comment by Jhonfunk** [comment]
default setting

**Comment by freedit-dev** [comment]
I think you've got the wrong culprit. Almost every http response contains Date header.

So What's your cloudflare default cache setting？Do you change it to `respect existing headers`?

In general, html will not be cached.

**Comment by freedit-dev** [comment]
You'd better disable `Brotli` compression. I have some problems with it.

**Comment by Jhonfunk** [comment]
> You'd better disable `Brotli` compression. I have some problems with it.

@freedit-dev 

Do you mean disable `Brotli` on cloudflare or disable `Brotli ` on freedit?

**Comment by freedit-dev** [comment]
@Jhonfunk cloudflare
