### ISSUE TITLE
`<meta name="keywords"` and `<meta name="description"` should be based on page content

### ISSUE THREAD

**Issue by Jhonfunk** [freedit-org/freedit#163]
Fixed `<meta name="keywords"` and `<meta name="description"` should only exist on the front page.

**Comment by freedit-dev** [comment]
Why? Sorry, I don't get it.

**Comment by Jhonfunk** [comment]
![sdfsdf](https://github.com/freedit-org/freedit/assets/78594391/95c5b0a4-42f1-407a-8e98-3d9460c0562c)

**Comment by Jhonfunk** [comment]
@freedit-dev
Basically it's the same thing as `<meta property="og:title"` and `<meta property="og:description"`.  Fixing the same `<meta name="keywords"` and `<meta name="description"` on every page is a disaster for seo, please withdraw this update!
