### ISSUE TITLE
On uploading/replacing avatars

### ISSUE THREAD

**Issue by kpishere** [freedit-org/freedit#171]
When you upload an avatar for a user, there is no cache flush on your browser so that new avatar does not take effect.

This happens when one is replacing the avatar with a new one.

**Comment by freedit-dev** [comment]
<https://freedit.eu/post/1/5>

Are you testing on local machine or behind Cloudflare? If behind Cloudflare, you need to change the default cache setting from `4 hours` to `respect existing headers`
