### ISSUE TITLE
The cargo run does not build

### ISSUE THREAD

**Issue by KosakaWakamo** [freedit-org/freedit#209]
rust : rustc 1.75.0

```
> rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Wakamo\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.75.0 (82e1608df 2023-12-21)
```

error: failed to run custom build command for `tikv-jemalloc-sys v0.5.4+5.3.0-patched`

Caused by:
  process didn't exit successfully: `D:\freedit\target\debug\build\tikv-jemalloc-sys-225e34d746ad4820\build-script-build` (exit code: 101)
  --- stdout
  TARGET=x86_64-pc-windows-gnu
  HOST=x86_64-pc-windows-gnu
  NUM_JOBS=4
  OUT_DIR="D:\\freedit\\target\\debug\\build\\tikv-jemalloc-sys-4cae72b20b506eee\\out"
  BUILD_DIR="D:\\freedit\\target\\debug\\build\\tikv-jemalloc-sys-4cae72b20b506eee\\out\\build"
  SRC_DIR="C:\\Users\\Wakamo\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tikv-jemalloc-sys-0.5.4+5.3.0-patched"
  cargo:rustc-cfg=prefixed
  cargo:rerun-if-env-changed=JEMALLOC_OVERRIDE
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-pc-windows-gnu")
  HOST = Some("x86_64-pc-windows-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-gnu
  CC_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_gnu
  CC_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-gnu
  CFLAGS_x86_64-pc-windows-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_gnu
  CFLAGS_x86_64_pc_windows_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  CC="gcc.exe"
  CFLAGS="-O0 -ffunction-sections -fdata-sections -m64 -Wall"
  JEMALLOC_REPO_DIR="jemalloc"
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_MALLOC_CONF
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_PAGE
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_HUGEPAGE
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_QUANTUM
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_VADDR
  --with-jemalloc-prefix=_rjem_
  running: "sh" "D:/freedit/target/debug/build/tikv-jemalloc-sys-4cae72b20b506eee/out/build/configure" "--disable-cxx" "--enable-doc=no" "--enable-shared=no" "--with-jemalloc-prefix=_rjem_" "--with-private-namespace=_rjem_" "--host=x86_64-w64-mingw32" "--build=x86_64-w64-mingw32" "--prefix=D:\\freedit\\target\\debug\\build\\tikv-jemalloc-sys-4cae72b20b506eee\\out"

  --- stderr
  thread 'main' panicked at C:\Users\Wakamo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tikv-jemalloc-sys-0.5.4+5.3.0-patched\build.rs:347:19:
  failed to execute command: program not found
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by freedit-dev** [comment]
Just use toolchain `stable-x86_64-pc-windows-msvc`

**Comment by KosakaWakamo** [comment]
> Just use toolchain `stable-x86_64-pc-windows-msvc`

thx

**Comment by freedit-dev** [comment]
You may need to `apt-get install make`

**Comment by KosakaWakamo** [comment]
> You may need to `apt-get install make`

Thank you. It's a perfect solution.
