### ISSUE TITLE
install help

### ISSUE THREAD

**Issue by atomGit** [freedit-org/freedit#267]
hi @freedit-dev - i like what you're doing with this project, especially the privacy aspect and no JS

i've never dealt with rust before and i'm not a very experienced server admin - can you elaborate on where the binary should be placed and security stuff (user, permissions)?

also how should the binary be run - a startup script, as a service?

**Comment by freedit-dev** [comment]
1. Did you successfully launch freedit on your local computer?
2. Do you have a vps?
3. Do you have a domain name?
4. Do you trust Cloudflare?

It doesn't matter at all that knowing nothing about Rust. Tell me what you have tried and what you have learned about server system administration.

If you want to deploy freedit in product, you need to deal with `https`. A Nginx or Cloudflare Tunnel is what you need.
