### ISSUE TITLE
Hi 👋

### ISSUE THREAD

**Issue by jan53n** [freedit-org/freedit#35]
i am new to rust, would love to contribute to this project. (don't know how)

**Comment by freedit-dev** [comment]
Welcome!

If you have read the [book](https://doc.rust-lang.org/book/) then you may try [axum](https://github.com/tokio-rs/axum) and [sled](https://docs.rs/sled/latest/sled/).

If you have any question, just mention me here.

**Comment by jan53n** [comment]
thanks
