### ISSUE TITLE
table style

### ISSUE THREAD

**Issue by freedit-dev** [freedit-org/freedit#42]
the table style is blank.

```markdown
| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |
```

**Comment by liamhession** [comment]
Hi, i'm learning Rust and searching for "first issues" where i might be able to get hands on experience. 

Based on the "Hi" issue opened by another first-timer, sounds like i might want to read up on https://github.com/tokio-rs/axum 

What would be some success criteria for this issue? Any guidance about what you're looking for, and any links to places in the codebase that could serve as an example of parts similar to what i'd need to create for this issue, would be a huge help!

**Comment by freedit-dev** [comment]
This question has nothing to do with rust, but css. Of course, you have to run it locally, which is very easy with the help of Cargo.

After setting, you need to register and post to see the effect.

If you are interested in rust, you may see [sled](https://docs.rs/sled/latest/sled/), just see it as a BTreeMap. Something that might be helpful.

* [model](https://freedit-org.github.io/freedit/freedit/controller/index.html)
* [admin_view](https://freedit-org.github.io/freedit/src/freedit/controller/admin.rs.html#99)

Thank you for your time. I might add more doc for development later.

![image](https://user-images.githubusercontent.com/107944572/216212127-7aeb039c-a58b-4fac-a221-e9b9d2ce227f.png)

**Comment by liamhession** [comment]
Ah okay, i have plenty of experience with CSS, was hoping to find ways to contribute Rust code to some project. Maybe i'll wait for the next "good first issue" in your project. Thanks for the reply!

**Comment by freedit-dev** [comment]
@liamhession I'm not good at judging project difficulty. Based on your skill in CSS, I'm sure you have some interest in rust web dev like freedit.

You can try https://github.com/freedit-org/freedit/issues/7.
