### ISSUE TITLE
Release Works-Cannot Create User

### ISSUE THREAD

**Issue by kirtcathey** [freedit-org/freedit#44]
When I clone the github repo and build, everything compiles fine but the app will not let me create a user... says wrong captcha, then says wrong password. Looks like a db initialization issue.

However, the release version works fine... any ideas. Am I missing a configuration somewhere.

Very interesting project and want to join in on the fun.

**Comment by kirtcathey** [comment]
Just confirmed that it is most likely only on the current version in the repository on Windows. Just compiled and works fine on OSX Ventura on intel.

**Comment by freedit-dev** [comment]
Thank you for your trying. I hope this would fix your problem.

https://github.com/freedit-org/freedit/commit/b3982b9df6c32cda1df53dccf440559856c11a0b
