### ISSUE TITLE
customize home page

### ISSUE THREAD

**Issue by freedit-dev** [freedit-org/freedit#47]

**Comment by johnhorsema** [comment]
Hi @freedit-dev, I want to contribute to improving the UI and frontpage design. I see freedit is using [Bulma](https://bulma.io/). Would you like to keep it or are you open to use like [WindiCSS](https://windicss.org)?

I have previously helped on improving UI at https://github.com/Shivansh-yadav13/SQLite-UI/pull/36.

**Comment by freedit-dev** [comment]
@johnhorsema Hi, thanks for your proposition. I chose bulma at first because it's  simple enough for me( I know nothing about frontend). I have tried tailwind too but it's too complicate comparing with bulma.

Honestly, I'm not sure what it'll be like with WindiCSS. If it looks better than Bulma, I will use it.

**Comment by freedit-dev** [comment]
I just tried TailWindCSS, it looks better than Bulma, but it needs more efforts. If I have more time, I'll try again.
