### ISSUE TITLE
avatar cropping

### ISSUE THREAD

**Issue by thomas992** [freedit-org/freedit#63]
It would be desirable to have image cropping dictated by the user after upload if it is not proper aspect ratio, anything other than (1:1)

**Comment by thomas992** [comment]
not foreseeable to do this without javascript

**Comment by freedit-dev** [comment]
That can be achieved in server side: <https://docs.rs/image/0.24.5/image/enum.DynamicImage.html#method.crop_imm>.

But I think it's kind of messy and not worth it.
