### ISSUE TITLE
gallery

### ISSUE THREAD

**Issue by thomas992** [freedit-org/freedit#64]
![gallery](https://user-images.githubusercontent.com/31554741/215855566-1d98a110-395c-4fc3-a84c-7784b50e29c6.svg)

was hoping to make a gallery user page, when images are uploaded I do not see a way to access them in a list after the initial upload complete screen.

**Comment by thomas992** [comment]
admin should be able to sort image uploads by view count too

**Comment by freedit-dev** [comment]
<https://freedit-org.github.io/freedit/freedit/controller/index.html#user>

`user_uploads` contains the upload info.
