### ISSUE TITLE
Some problems encountered when running locally

### ISSUE THREAD

**Issue by Yakumo-Yukari** [freedit-org/freedit#77]
![123](https://user-images.githubusercontent.com/12076232/220098282-b58dd93e-f3e0-4907-8082-d124c50228b4.png)
![11113](https://user-images.githubusercontent.com/12076232/220098296-5a66251d-1c2c-47f0-b81f-5165cdad9ea6.PNG)

1. Joe and joe will be identified as 2 users

2. When logging in, if you enter a space, you will be prompted with a wrong password, and the extra space will not be deleted automatically

3. Can't login after registration, after clicking login, it will jump to the home page but the user is not in login status

**Comment by freedit-dev** [comment]
https://github.com/freedit-org/freedit/blob/5d8e70ee25354493bed9abfa5a7fbec9c4ae55ec/templates/signup.html#L19

related to `pattern="^\D\w*"`
