### ISSUE TITLE
Can freedit add such a feature in the list of posts to show a summary of the content and images in the content

### ISSUE THREAD

**Issue by Yakumo-Yukari** [freedit-org/freedit#78]
![3](https://user-images.githubusercontent.com/12076232/220585981-e7809dd7-b03f-47e9-ac37-0e391b4bffb0.png)
![2](https://user-images.githubusercontent.com/12076232/220586020-fa2434f9-b33d-4d08-88e8-ab865f8cc703.png)
![127](https://user-images.githubusercontent.com/12076232/220586036-d2050849-cfa5-4cc7-9554-a0367f6d4003.png)

**Comment by freedit-dev** [comment]
Yeah. It's a good feature but I can not promise anything.
