### ISSUE TITLE
Insert audio in the article

### ISSUE THREAD

**Issue by apt-007** [freedit-org/freedit#84]
https://github.com/raphlinus/pulldown-cmark/pull/631/commits/d0814094f87eb8783032c35be86f6f945580efbd

**Comment by apt-007** [comment]
https://github.com/raphlinus/pulldown-cmark/pull/629

**Comment by freedit-dev** [comment]
Adding this feature is not a difficult task, but it does require the use of https://github.com/video-dev/hls.js/ which means that it is not free of JavaScript. However, I am considering allowing the use of some JavaScript, perhaps in the form of a parallel release.
