### ISSUE TITLE
"This attempt to set a cookie via a Set-Cookie was blocked..." error on Chrome and Edge

### ISSUE THREAD

**Issue by dominikdalek** [freedit-org/freedit#86]
Cookie is never set on Edge and Chrome due to cookie rules violation.
Error points to: https://datatracker.ietf.org/doc/html/draft-west-cookie-prefixes-05

This happens when testing locally w/o TLS and set-cookie issued with value `__Host-id=###; SameSite=Strict; Path=/; Secure; HttpOnly; Max-Age=14400`

As a workaround it probably makes sense to use a different cookie name when freedit runs locally on http. But I think it would be best to disallow insecure setups altogether and provide steps for cert/key generation.

**Comment by freedit-dev** [comment]
Thanks for your feedback. I just test it with Firefox.
